version: 0.0
os: linux
files:
  - source: /
    destination: /App
permissions:
  - object: /App
    pattern: "app"
    owner: appuser
    group: appuser
    mode: 755ß
    type:
      - directory
hooks:
  ApplicationStart:
    - location: service_restart.sh
      timeout: 300